###########################################################################
# Ingress resource (gateway)
###########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  tls:
    - secretName: istio-ingress-certs
  rules:
  - host: open.d10l.de
    http:
      paths:
      - backend:
          serviceName: developer-portal-ui
          servicePort: 80
        path: /.*
  - host: api.d10l.de
    http:
      paths:
      - path: /identities/.*
        backend:
          serviceName: identities
          servicePort: 9090
---
###########################################################################
# Egress resource (gateway)
###########################################################################
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: auth0api
  namespace: default
spec:
  destination:
      service: "d10l.eu.auth0.com"
  ports:
      - port: 443
        protocol: https
---